version: '3'

services:
  backend:
    container_name: 'backend'
    networks:
      - db
      - api
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    ports:
      - '4000:3000'
    depends_on:
      - database
  
  database:
    container_name: 'database'
    networks:
      - db
    image: postgres:12
    restart: always
    env_file: .env
    ports:
      - '5432:5432'

  frontend:
    container_name: 'frontend'
    networks:
      - api
    build: ./frontend
    ports:
      - '8081:80'

networks:
  db: 
    driver: bridge
    internal: true
  api:
    driver: bridge